apiVersion: v1
kind: Service
metadata:
  name: github
  namespace: trojanhk
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: github
  sessionAffinity: ClientIP
  externalIPs:
    - 10.0.0.6
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github
  namespace: trojanhk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github
    spec:
      containers:
      - name: github
        image: 1635537446/action-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 30Mi